* アラブ革命はなぜ起きたか
  (男性の)識字率が上がる, 革命(異議申立て)が起こる、(女性の)識字率が上がる、出生率の低下が起こる。
  革命後の政治形態は、その国が持つ家族形態によって決まる。
** アラブ革命は予見可能だったか？
*** アラブ革命とイラン革命
    同じもの。イスラム的人間はない。
    家族生活の中での自由と合理性の発達が、政治的な大変動につながる
*** 若者による街頭革命
    革命とは、人々が街頭に繰り出して、公然と体制に意義を申し立て、　軍が崩壊するか、体制から離れる。
    年齢の中央値、チェニジアで29歳。エジプトで25歳。
** 識字率・出生率と民主化
*** 識字率
人類の歴史の中心軸=> 識字率。プロテスタント宗教革命から大衆識字化が始まる。
*** ビラの読み書きと政治参加
フランス革命はパリ盆地の男性50%が読み書き可能になって起こった。
イングランドもロシアもイランも同じ。
*** 出生率
識字率の上昇 => 革命 => 出生率の低下　という順番で起こる。
出生率の低下は、女性の識字率の上昇に伴う。
子どもの数を決定するのは、神ではない。
** 誤解されているイラン革命と現体制　
*** アラブ圏に３０年先行したイラン革命
    革命の結果が、権利主義体制になることはある。
*** 外敵勢力にブレーキをかけられた民主化
    イラン・イラク戦争でブレーキ。
    アラブ社会における出生率の低下は、社会の変化を物語る
*** 単一でない民主化プロセス
    トッドのモデルは２つ。
    1. 識字率の向上から始まる政治的変動
    2. 変動の出発点の違い。=> その時点での家族形態が持つ価値観によって違いが生まれる。
    ヴォルテールもモンテスキューの思想も、２の家族形態が生み出した思想で、偶然フィットした。
    識字率の向上が、家族内での権威に打撃を与え、社会内での権威に打撃を与える。
** イスラーム圏の内婚制と近代化
*** 内婚率
    民主主義の出現は、自由なる個人が公的空間に出現
    内婚はその反対。父系（子どものステータス=>婚姻関係の組み方?は父親できまる)のシステムで男性が重要。
    チェニジアは若者の識字率が95%ほどだが、いとこ婚が35%ある。
** チェニジアとエジプトの内婚率
   世代ごとの内婚率が重要。
   エジプトの内婚率は急激に低下。エジプト社会の急激な変化を予期させる。
** トッドの手法
*** アナール派的長期分析
   トッドは、ソ連の崩壊、シラクの当選などを当てる。
   アメリカ帝国の衰退(具体的にはわからん)
   現在、ユーロの終焉を予測。
** アラブ圏の民主化とフランス
*** フランスは何の脅威にも晒されていない。
    フランスとマグレブ(北アフリカ西部、チェニジア、モロッコ、アルジェリア)の関係。脱植民地化=>出生率の低下が進む
    もともと遅れた地域だったが、フランスとの交流で進歩
    首長国については、石油収入が近代化（政治形態の変化?)にブレーキをかけている
** 宗教は関与していない
   ハンチントンの文明の衝突に対して、文明の接近を書いた。
   宗教は家族形態の構造に関与していない。
   出生率２を下回る場合、それは宗教的信仰の崩壊が起こってる。イランの問題はナショナリズムの問題。
   遺産相続についての、マホメットのアイデアは受け入れられてない。
   コーランは民法典(フランスの民法?)のレベルで守られていない。
** 老化という西欧の危機
   カトリックを信じない人増える => 宗教を信じるバカがいない、バカにする相手がいない　=> イスラム教を信じるやつをバカにする
   内婚制社会（女性がいとこ と結婚)には、家族メンバー内に敵意が存在しない。
   外婚制では、敵意やはげしい人間関係
** 中国とロシアの民主化
   中国は枢要。民主主義が普遍的かどうかという問題の。
   中国では、選別的女性胎児殺しが行われている。近代化における退行減少ともいえる。
   ブラックアフリカ: ルワンダの家族形態はドイツに似ている。不平等主義的システム
** ドイツ
   直系的家族システムのドイツ、日本、ルワンダ
   ユダヤ排斥、日本神国、ツチ族への優位　という運動を生む。
   ドイツと日本は、鎮静化した本物の民主主義国。
   諸文明の収斂はあるが、人間類型への接近はないよ。
** 民主化・進歩とは何か？
   ナチズムは自力で崩壊したわけでない、ロシアは自分でシステムを放棄した。
   ドイツは西側民主主義陣営から滑り落ちつつある？？？
   ドイツは本物の政権交代型民主主義でない
   西洋民主主義の中核は、イギリス、フランス、アメリカの３国。トクビルの世界。
   ドイツでは、赤信号でも止まらないことや、電車の遅れなどが見られてきてる =>　進歩？でしょうか？
   進歩とは、、、大衆知識化への道のり
** 人口動態からみたアラブ民主化
   民主主義の形
   アングロサクソン、フランス=> 政権交代型
   スウェーデン、ドイツ、日本 => 全員一致型民主主義
   東アジアの出生率は低いが、インドネシアは２に上でとどまっている。
   チェニジア: フランスは特に何もしてないが、フランス語と避妊技術を通して、フランスのソフトパワーが浸透
   エジプト: 家族構造は、他のアラブ諸国のように父系原理が絶対でない。内婚率が低下傾向。
** トッド人類学入門
   




