キーシンジャー:外交
知識がないので、章ごとにある岡崎久彦の解説を抜き出し。それのみ。

* 新しい世界秩序
  アメリカ外交の本質と、その対極にあるバランスオブパワー
* アメリカ外交戦略の軸
  ウイルソン主義の本質
  パワーポリティクスへのアンチテーゼ
  ルーズベルトは異端
  ベトナム問題とウイルソン主義
* 普遍性から均衡へ
バランス・オブ・パワーの元
国家の存在、国家の行動を律するのは国益、
国益の追求=>衝突=>バランス・オブ・パワー
バランサーの役割がイギリスに
* ヨーロッパ協調
ウィーン体制は安定した型
メッテルニヒの外交　=> 失脚 =>クリミア戦争=>ドイツの力が膨張
* 二人の革命的指導者　ナポレオン３世とビスマルク
パワーポリティクスの時代へ

* リアルポリティークの独走
  強大国になってしまったドイツ　ビスマルクの手腕
  ロシアの役割
* 破滅に至る政治的仕組み　第一次世界大戦前夜のヨーロッパ外交
  ドイツ、ロシア、フランス、イギリス
  ドイツの伸長がもたらしてたものへの分析
* 渦の中へ
  些細な危機が破滅(第一次世界大戦に)
  軍事計画。外交官と軍部
  各国が約束を守ったため、大戦が始まった。
* 外交の新顔
  ウィルソン主義の登場
  大衆同士の総力戦＝徹底的な勝利を求める=>ニヒリスティック
  国際連盟　ドイツの脅威の増大
  
* 戦勝国のジレンマ
  独ソという二大大陸国家の接近
  ベルサイユ体制の欠陥=>同盟と集団安全保障の違い。
  同盟には仮想敵国があるが、集団安全保障は国際法を守るにすぎない。機能
  しない。また、勝者と敗者を区別しないのは問題だった。
* シュトレーゼマンと敗戦国の再登場
  シュトレーゼマンはベルサイユ体制に協力したが、、、実は外交でドイツ
  の、、
  ケロッグ・ブリアン不戦条約＝>無意味な内容ゆえに反対できず=>日本憲法
  の源流に。
* 幻想の終焉
  ドイツ軍のラインラント進駐。ヒトラーの進出。
  イギリスの雰囲気が一変。
* バザール商人、スターリン
  資本主義同士を競わせ、ソ連邦が戦争の犠牲になるのを回避。
  ドイツと西側諸国に戦争がおきることがはっきりすると、ドイツに接近。
  東ヨーロッパを手に入れる。
* 独ソ不可侵条約
  チャーチルは、ドイツの覇権より米国の覇権。英米協調路線。
  ヒトラーは、イギリス攻撃に失敗した後、独ソ戦に走る。
* アメリカの再登場
  ルーズベルト、国家戦略として参戦への手を着々と打つ。
* 和平への３つのアプローチ
  ルーズベルト、チャーチル、スターリンの政治哲学
  スターリン: ソ連邦の周りに安全地帯を設ける。
  チャーチル: スターリンに抵抗。フランス再興、ドイツ復興。
  ルーズベルト:　チャーチルに反対。イギリスの植民地帝国の復活に反対。
  ルーズベルトの戦後構想は楽観的すぎた。しかし、それはアメリカが通過し
  なければいけないものだった。
* 冷戦の始まり
  スターリンの衛星国の設立
  ただ、スターリンは譲歩する余地（取引を望む)を持っていたが、西側は利
  用できず。
* 封じ込め政策の成功と苦悩
  ケナンの封じ込め政策。
  ソ連の敵意とその政策は、構造的なものであり、宥和する余地はない。
  アメリカの封じ込め政策の批判
  1. 手を伸ばしすぎ、国力を疲弊。ウォルター・リップマン
  2. 防勢的なだけ。チャーチル。
  3. 倫理的に優越してるわけでない、共存すべき。ヘンリーウォレス。
* 封じ込め政策のジレンマ
  戦争が欧州でなく、朝鮮で起きた。
  ソ連を過大評価してしまっていた。全面戦争で全てを失うのはソ連だった。
  悪に対する戦いと捉えたアメリカのナイーブさ。献身。指導的立場の確立。
  軍事支出の増加。軍事バランスを西側優位に。
* 共産主義者との交渉
  スターリンの死の直前、朝鮮戦争の終わりから、１９５６年のスエズ、ハンガリー動乱までのジュネー
  ブ精神の時期。
  お互いのブロックでの支配が固まる。
  ソ連は東側に優位が生じたと過信＝＞フルシチョフの冒険に。
* 封じ込め政策の迂回
  スエズ危機。英仏の影響力喪失。後進国はパワーゲームを覚え、ナショナリ
  ズムへ。英仏なし、独力でアメリカは世界に立ち向かう。
* ハンガリー
  国際世論は西側批判に。
  ダレス: 東ヨーロッパは扇動。。したが、アメリカは手を出さず。
  アメリカとしては、大きな戦争になる危険を犯せない。
  ただ、ソ連にとっては、最終的に衛星国を抱え込む負担が大きい。
* フルシチョフの最後通牒
  スエズ、ハンガリー動乱で西側が後退をフルシチョフは認識。
  アイゼンハワー、マクミランの宥和政策。
  アデナウアーは東ドイツの未来は、東西ドイツに委ねるのではなく、西側同
  盟の結束に基盤を置く。
  結局、ベルリンの壁の構築で終わる。フリシチョフは、キューバ危機後に、
  舞台を去る。
* 西側同盟とは
  スエズ以降、フランスは自立化へ。イギリスは米国とのパートナーシップの
  強化へ=>力を持つ国から影響力を持つ国へ。マクミラン。
  ドゴールは、フランスの自尊心を追求。国家理性に基づくもの。
* ベトナム、泥沼の中に
  アメリカ的価値観からベトナム介入の動機にはあるが、介入は地政学的論拠。
  ドミノ理論。ミュンヘンの記憶。宥和政策は高くつく、、
* ベトナム、絶望への道
  フォン・ドン・バン: アメリカは軍事的には優位だが、ベトナム人はベトナ
  ムのために死のうとし、より長く戦う用意がある。
  アメリカが勝てたかもしれない可能性
  1. ラオスを守る。
  2. 中国が介入しない可能性を見極め、ハノイへの軍事的圧力を強化する
  3. テト攻勢の際に、もう一度勝負に出ていれば、、、
* ベトナム撤退
  撤退以外の選択はない。
  和平協定。しかし、北ベトナムは南を併合。
  「いかに分裂しても最終的には結束できることに自信を持ち、あえて自らを
  引き裂くような社会、再生を促すための分裂の危険を犯すような大胆な国民
  はアメリカ人の他にはありえない。」
* 地政学としての外交
  米中国交正常化にあたっての思考。
  米中の国益が一致する点について、それぞれが他方を支持する枠組みを作っ
  た。
  リアルポリティクスは、感情的な共感がエられず。
* デタント、それに対する反対論
  デタント時代。ヘルシンキの全欧安保協力会議。
  軍備管理問題。これが強調されると、国防政策には潜在的な脅威となる。
* 冷戦の終わり
  レーガン。アメリカ的信念。
  ジョージ・ケナンの予言通り。ソ連崩壊。
  アメリカが、バランス・オブ・パワーを認識しなかったが、その価値観で冷
  戦を勝ち抜いた。
* 新世界秩序再考
  最終的には、アメリカもバランス・オブ・パワーの中で動かねばならない。
  イギリス型? ビルマルク型？イギリス型は不可能。
  
