本のまとめ: 米国金融史７章ー大収縮(1929-933)を読んで。

* 貨幣、所得、物価、貨幣流通速度、利子率の推移
** 株式市場の大暴落 1929/10
   金融面への影響は株式市場のみにとどまる
   1929年８月景気循環のピーク。株式相場も1929年８月がピーク。
   貨幣流通速度の急落(通常の景気後退でも下がる）
   マネーストックの減少（主にFRBの信用残高の減少)
   特にこの段階では、銀行への不信はない
** 第１の銀行危機の勃発 1930/10
*** 1930/12 合衆国銀行(一般の商業銀行,預金額は大きい、FRBの加盟銀行)の破綻
      名前から来る心理的なダメージ、また手形交換所の加盟銀行が、協調救済されない、、、
***   1931年初頭から、景気回復の兆候が出、預金・現金比率、預金・準備比率の上昇、マネーストックの増加があるが、、
***   FRBの信用残高の減少で打ち消し、、、、
** 第２の銀行危機の勃発 1931/03
   大衆の現金化再開
   米国の後退が、海外に悪影響。米国への資本逃避(金ストックの増大)
   金ストックの増大では、預金者、銀行の防衛的行動を相殺できず、マネーストックの増加にはならず
   低格付け債券の下落で、銀行のポートフォリオの劣化=>売却で悪循環　   政府債の上昇
** 英国の金本位制離脱 1931/09
   １９３１年９月１２日、イギリス金本位制離脱
   米国が標的に => ニューヨークの金融市場で、ドル売り金買い
   秋は通貨需要が高まる時期、その時期に、米国の銀行制度から通過が流出
   国外流出に対抗して、FRBは金利引き上げ。買いオペは行われず。。。
   銀行は、FRBからの買い入れと、資産の投げ売りを実行。
   ただ、借入は、市場から悪い評判を呼ぶので、抵抗。
   全米信用組合を設立して、協同組合の加盟銀行の共同保証で融資したが、足りず。(1914年には復興金融公社が成功したが)
   担保の拡大などを行うが、、、
   財政赤字こそが危機の主因？？　１９３２年6月に増税を実施。
** 公開市場での大規模な買いオペの開始 1932/04
   あらゆる利子率が急落。CPが公定歩合を下回る。
   卸売物価は７月、工業生産は８月に底打ち
** 銀行恐慌の発生　1933
   １９３２年７月の法令。RFCの貸付先の公表(法律では議会と大統領への報告だったが)
   => 脆弱な銀行との烙印。取り付けに。
   バンクホリデーの続出
   1933/3/6 全国的なバンクホリデー（過去にも現金支払い制限はあったが、その時は通常の業務は続けられた)
   銀行の資本が脆弱だったのも原因。買いオペをしてれば、資産価値が上がっていたのだが。1932年8月に終了していた。

* マネートスックの変動の諸要因
  本で使われる用語
  マネーストックは、マネーサプライと同義。
  現金預金比率(預金/市中通貨量(マネーストック?)) => 大衆の銀行への信任に左右される？
  預金準備比率(預金量/準備金量)　=>
  ハイパワードマネー、現金預金比率、預金準備比率で、後者２つでマネーストックは減少。
** 株式市場の大暴落1929/10
   株式市場暴落時の証券　
   - 長期証券を現金化したい。誰かが買うしか無い。価格下落でバランスするだけで、現金化はできない。
   - コールローン　=> 貸付総額が変化。精算するので、貸付総額は減少。
     1. 貸付債券の移転先を見つけないといかん。=>利子率の上昇
     2. 現金化したい => 資産価格の減少
     3. うまくやって、お互いに負債をバランスさせる(cancelできればする。できなければ付け足してバランスさせる)
   １０月の暴落は、ニューヨークの銀行が貸付債券を引き受け。うまくやった。
   NYの銀行の預金増加には、NY連銀がFRBに諮らずに買いオペ
** 第一の銀行危機の勃発 1930/10
   預金・現金比率の低下
   そして、預金準備比率も低下へ
   FRBは、金流入を不胎化してしまう。
   ２月に好転したものの、チャンスの逃す。
** 第二の銀行危機の勃発 1931/03
   長く悲惨に。
   第一の危機では信用残高が一時的には上昇したが、今回はそれもなし。
   公定歩合の引き下げが行われたが、それ以外は、FRBの行動はなし。
** 英国の金本位制離脱 1931/09
   次の標的として、米国の金流出。市中銀行への貸し出しは増える。
   しかし、銀行は預金に対する準備の比率の引き下げができず、市中通貨を創りだすために、準備をを引き下げる。
   預金の減少に直面　　　　　　　　　　　
** 公開市場での大規模な買いオペ 1932/04
   当初の４ヶ月は効果（マネーストック増大)出ず。
   金流出の収束、担保にできる政府債の範囲拡大などが効果。
** 銀行恐慌の発生 1933
   金貨・金証券への嗜好が強まる。(よくわからん)
* 銀行破綻
** 銀行破綻が果たした役割
   銀行破綻は、マネーストックを撃滅させる。同時期にカナダでは銀行破綻せず、マネーストックの撃滅とはならず。
** 銀行破綻の原因
   融資の質の問題？銀行自身の行動が不適切？
   決定的だったのは、銀行がハイパワードマネーを獲得できず、預金者の通貨需要を、準備の減少でしか賄えなかったこと。
** 連邦準備制度の対応
   合衆国銀行の破綻はニューヨーク連銀にも衝撃。
   銀行の破綻 - 預金の収縮 - 債券市場の弱体化　この関連性の理解が甘かった。
   また、非加盟銀行の破綻には責任を感じてなかったのも、対策の後れに。
* 大収縮の国際的特質
  1929年、多くの欧米諸国は金為替本位制
  金に対する支払い要求額が相対的に増える。現実に持つハイパワードマネー
  に対して？　世界各国が関連しあい、景気後退が波及。
  米国は、金の流入を不胎化。=> マネーストック増加せず。
  銀本位制を採用していた中国は、不況にならず。
  金本位制を離脱した国から、不況脱出。
* 金融政策の推移
連邦準備制度内部の権力争い。ニューヨーク連銀と連邦準備局の対立
** 株式市場の暴落1929/10
   ニューヨーク連銀とFRBの対立
   NY連銀は、株式急落に果断に行動
** 第一の銀行危機の勃発1930/10
   
** 第二の銀行危機勃発1931/09
** 英国の金本位制離脱 1931/09
** 公開市場の大規模な買いオペ 1932/04
** 銀行恐慌の発生
* 代替策
* なぜ極めて的外れな金融政策がとられたのか？

* バーナンキの所見
  １９２９~1933の経済破綻は、金融メカニズムの問題
  金融的変化が外因性だと認められる限り、そこからの経済の反応には因果関係があると推定される
  ４つの時系列の例だけでなく、地域横断的な事実もある。金本位制からの離脱段階と、経済回復の段階の一致。
  １９１３年の連邦準備制度の導入は、銀行恐慌への対処だったが、1930年の恐慌には対処できなかった。
  むしろ、少銀行の破綻の放置から恐慌は悪化。
  ストロングの死がもたらしたもの。適切な政策が取られなくなったという比較はできなくもない。
