* ユートピア株式会社　
** 会社の威力
   富を生んだ。社会を変えた。個人を変えた。
   社会の最重要基本単位。
   人間と同じ法律上の権利(法人格?)がありながら、不老不死。
** 会社の変遷
***   19世紀のイギリスの変革
   1. 法人
   2. 権利の債券化
   3. 出資以外に責任を追わない(有限責任)
有限責任が機能するかの議論。
エージェンシー問題の議論
この後、20席のアメリカで巨大企業が生まれていく
      
** 本書の狙い
***   論点は３つ
 1. 昔の会社はドラマティックだったので、書く。
 2. 倫理化した現代の会社ということ
 3. この会社制度を生んだ欧米の競争優位を説く。
*** 会社がもたらすもの
    資本の集約
    資本の開放(政府や同族集団の中から外へ)
    国家、教会、労働組合は太刀打ちできない。
*** 会社の存在理由　一つ一つの会社自体は強くない
    経済活動における取引コストの最小化が存在意義。
    取引コストの削減と階層コスト(本社が情報を見落とす)の差で考える。
* 貿易商人と独占商人の時代(bc3000-ac1500)
** 古代の商業活動
  メソポタミアやアッシリアで契約による経済活動
  フェニキア人とアテナイ人が海上活動に投資形態の契約
  ローマの徴税業務。個人からソエキタスに。その後ギルドに。
  会社法のいくつかはローマ時代に。集団をアイデンティティとする。
** 東方世界の繁栄
   アラブをもともと商業が盛ん。だが、相続が細分化され資本が分散
   中国は技術力に秀でる。だが、強い国家が貿易を制限 1400年代。明の永楽帝の死後。
** 中世の商業活動
***  イタリアが生んだ貿易会社。
     複式簿記の採用。海外事務所の不正防止のため
     為替の発達。銀行の発達。メディチ家。その後、不良債権を抱え没落。
     帳簿、弁護士、パートナーシップ契約、現代と同じ管理業務に忙しい。
** 近代的会社との相違はあるか
   特に強調してかかれてない。
   法人、社団の存在。死なない為に所有が国家に還されることがない。agaist封土制
   ギルドの伸長。国家からの貿易独占権
* 帝国主義者と投機家の時代(1500-1750)
** 大航海時代が生んだ特許会社
   特許会社。到達した地名がつくものがたくさん。
   政府と商人が共同で設立。特許状。
   売買可能な株式。有限責任 => 株式市場
   オランダ東インド会社
** [栄光の会社]と帝国主義
   イギリス東インド会社
   - 二層構造の採用。株主総会で取締役を選任、委任。
   - 現地の管理はファクターと呼ばれる人間に。
   - 徐々に衰退。1874年消滅。
** バブルの痛手
   ジョンローのバブル。
   政府の負債を株式と交換。貿易独占権の付与。
** 会社の功罪
*** 問題
    会社は罰することができない。
    アダムスミスの批判。特許会社の独占。エージェンシー問題。
*** 良い点
    スペインのように国家が帝国主義を行うより、会社に任せるほうが、
    結果として、帝国主義の実践として良い。
    東インド会社での、ファクターによる取引は効率的だった。
    カンパニーマンの育成。その手の人間にやすらぎの場。
* 長い苦痛の末の誕生(1750-1862)
** 不遇の時代
   １７００年代、１８００年代、株式会社は不人気。
   イギリスでは株式会社で事業を行うには特許状が必要だった。
   パートナーシップが人気。奴隷貿易も特許状を得るものから、パートナーシップへ。
   所有と経営の分離はうまく行かないと考えられていた。
** アメリカの選んだ道
   特許状を与えて、インフラ整備。ただ、その特許が変更されてしまう。
   ウォール街も未成熟。国債取引が中心。
** 会社の自由化
   アメリカの各州で自由化が始まる。
   １８００年代、フランスでも、ジョンローの記憶薄れる。
   巨大な資本を必要とする鉄道整備がきっかけ。優先株による資本整備。鉄道専門誌=>相場情報
** 近代的会社の成立
   １８５６年、イギリスの株式会社法=> 7人が定款に署名。事業所の登記。limited(有限責任)を入れる。
   後年、ドラッガーは、政府から独立した自律的な組織が、社会の中に生まれた。
* アメリカにおける大企業の台頭(1862-1913)
** 個人事業から大企業へ
   シアーズローバックの誕生。１９１６年、従業員のための年金基金。=>大半は自社株投資。
   １９００年台、アメリカの大企業が躍進。
** 鉄道会社の大企業化
   輸送システムと通信システムの発達。
   膨大な管理業務の発生。近代的企業。
   １８００年代後半からの、アメリカの鉄道株投資。ただ、持ち合いが多く。銀行借入が多かった。
   合併により巨大化。物流の効率化進む。
** 小売業と製造業の大企業化
   鉄道網が巨大小売業を作る。１８００年代後半。
   遅れて、製造業も発展。カーネギー、フォードの流れ作業。
** 止まらない巨大化
   統合型巨大企業は、購買から宣伝まで規模の利益を得る。
   トラストを利用(配当を受け取り、議決権を放棄)して、信託に権利を集中。
   信託契約が無効になると、持ち株会社を作る。
   USスチールもパートナーシップだったが、それが株式公開へ。
** 危機感と反発
   労働組合も発展。
   1913年にアメリカでも中央銀行（FRB),1914年にクレイトン反トラスト法。
   労働者から経営者の夢。
** それでも支持された理由
   政治への進出。
   年金基金。福利厚生。
   慈善事業、美術館、博物館。
   会社による生産性の向上、そして豊かさの到来。
* イギリス　ドイツ　日本における大企業の台頭(1850-1950)
  ドイツと日本では、株式会社は社会に使える存在。
** 大企業化に後れをとったイギリス
   同族企業と個人的経営の執着。
   会社は、文化的な生活の一目的。上品ぶって、金儲けに嫌悪。
   田園都市構想
** 独自の企業モデルを発展させたドイツ
   独占や半競争的なものに寛容。
   企業は国益のために動くべき。
   監査役会の権限。構成員は銀行から政治家、労働組合まで。
   訓練好き。教育好き。軍隊は下士官に権限。工場長は経営管理者にアドバイス。尊敬される。
** 政府と財閥が牽引した日本
   明治以降の発展に政府の役割の大きさ。
   財閥による集中と能力主義。
* 経営者資本主義の勝利(1913-1975)
** 事業部組織と経営管理主義
   孤立した共同体社会だったアメリカを国家共同体に。
   新興資本家から専門経営者の時代。
   管理された分権化。スローン。事業部制。
** 経営理論家とカンパニーマン
   テイラー、アーサー・D・リトル、マッキンゼー
   カンパニーマンをそうたらしめてるのは、学校の成績。
   家族主義。
** 会社の役割
    市場の不完全性、取引コストを調整する。
    経営と所有の分離。コーポレートガバナンス。
    ドラッガー。知識労働者という呼称。
** 経営者資本主義と国家主導型資本主義
   第二次世界大戦以後の国有化の流れ。　
   これは、スローンの考え方といっしょ。上手に管理する。イタリア、フランスなど。
** 着実な発展
   目標による管理。
   カンパニーマンによる安定の時代。
* 会社のパラドックス(1975-2002)
  民間資本の勝利。
  大企業では、事業部制・終身雇用が崩壊。
** 株式会社の拡大
   サーチャーとキース・ジョセフの企業化。
   ソ連、東欧、中国の変革
** 生き残りをかけた改革
   大企業の没落。リストラの嵐。
** 日本型モデルの躍進
   アメリカの会社を解体したもの。日本企業、ウォール街、シリコンバレー。
   スローン主義=>品質管理は経営管理の仕事。日本式の衝撃。
** ウォール街という戦場
   機関投資家の影響力。
   企業買収家の勃興。ジャンク債の登場。
** IT産業がもたらした変革
   製品による変革。PC,ネットワーク。
   会社のスタイル。徹底した能力主義。
** 不確実性の時代
   安定が失われ、経営理論が流行る。
   カンパニーマンがヒーローから降りる。
   企業に求められる社会的責任。
** 企業倫理と規制
   バブル崩壊とエンロン事件。
* 影響力の代理人ー多国籍企業(1850-2002)
** 多国籍企業の歴史
   中世のイタリアの銀行家が始まり。法王の代理人で教会の税金徴収。
   次に東インド会社のような特許状企業
   鉄道事業が本格的な世界展開。イギリスからヨーロッパへ。また、資源採掘型も。
   その後、一般消費財。
   関税の高まりに対抗するため、輸出から現地化の必要性。
** 各国の多国籍企業
   イギリス。海外展開は早いが、もともとの素人的経営が海外でも足かせに。
   ドイツ。ハイテク分野で成功。
** 多国籍企業と帝国主義
   ベルギーやフランスの今後での収奪。
   制度の創設やインフラの整備も。
** アメリカの多国籍企業
   海外の需要に応じるうちに進出。関税化や貿易障壁と作られると、現地化。
   ジェット機で、大西洋を７時間。
   １９７１年以降のドル切り下げで、海外資産が割高に。省エネ機器で出遅れる。
** 多国籍企業とグローバル化
   貿易、投資が伸びる。
   中小企業も国際化。
   大企業内部では、世界単一市場対応。社内部門を統一。
** ２つの顔
   多国籍企業は闇の支配者か？
   搾取はできなくなっている。貢献（学校や病院の建設)
   最大のポイントは、生産性の改善を通じた性格水準の向上。
* 会社の将来  
** 進化する会社
   会社の進化。
   政府の道具=>小さな共和国=>カンパニーマンによる安定・官僚化=>企業家
   ２つのポイント
   - 取引コストと階層コスト、どちらが大きいか？
   - 政治的論理。社会に求められるものか？営業許可が与えられているか？
** ３つの将来像
   1. 大企業の支配が進む？進んでない。（俺: 最近はすすんできたかも???)
   2. 小規模化。技術の進歩で取引コストが低下。階層コストが問題になる？=> 力を持ち続ける大企業も多い。
   3. ネットワーク型。ネットワーク自体には、法人格も監査制度もない。
** 社会との関係性
   政府から特許状をもらう必要はなくなった。
   雇用を生む=> 政府や自治体が誘致する。
   社会からフランチャイズされないといけない。腐敗から見を守る必要もある。
   短期的利益以上の目的に向かっている。（俺: 生存本能?)慈善活動。
   豊かになる道具。
   社会が会社に働きかけるものに注目。企業責任強化運動。
   
* 訳者解説
このような本がまれな理由
- 分野が多岐にわたるため、人材がいない
- 企業は自由に設計するものであり、歴史的経緯に焦点があたりにくい  
訳者による会社の歴史的発展のまとめ
1. 古代の共同出資
2. 法人格の成立（中世の欧州、日本でも)
3. 有限責任 => 大規模資本　東インド会社
4. 特許主義から準則主義への移行
** 会社の規模拡大による国際化と国民経済との摩擦
その中で、国別に会社の発展の独自性を見る。
訳者による国別の会社モデルの優位性解説
   
