http://www.amazon.co.jp/gp/product/4489020651/

* 仮説検定とは(二群の平均値差を例に使って)
** 実験を計画しました
実験群と対象群を無作為に割り当てた。
** どうして検定が必要なの
平均点が9.25違う。実質的な差がある。でも、たまたまか？　乱数表でもそうな
る時あるよ。
** そもそも検定ってなんですか？
２つの標本平均が分かった。母平均に差があるか？
帰無仮説として、２つの母平均に差がないとする。
その前提では、非常に起きにくいことが起こった。=> 対立仮説を採択。
** まずは検定をしてみよう
t.test(実験群、対照群, var.equal=T)
t値=> (標本平均の差/標準偏差) * sqrt( (Nj * No)/(Nj + No))
このT値の分布は既知なので、今回のT値が分布のどこらあたりか？=> そうな
る確率がわかる
** 「起きにくい」ってなんだろう(有意水準)
帰無仮説を前提とした場合に、今回のようなデータが起きるのは、どれくら
い？
** 差の大きさを見積もろう(信頼区間)
帰無仮説を前提した場合の、確率の範囲を設定すると、その確率に入る平均値
の範囲。
ちなみに、標本数の平方根に反比例する。標本数が４倍で、範囲は1/2倍。
** 帰無仮説が採択されたら
   対立仮説をを採択することはできないだけ。帰無仮説が正しいとはいえな
   い。
   信頼区間と実質的な差に注目する
** 差とは何か？（効果量)
   ２群の平均値の差を、共通の標準偏差で割ったもの
   これは、(t値) * (標本数の関数)になる。
** 両側検定・片側検定
両側検定でOK.片側にしてｐ値を半分にできるけど、片側でいいと誰が決める？
** 有意水準と効果量は別？
効果量があっても、有意水準に足りない場合は、標本数が足りないとして、判断を保留するしかない。
** 実質的差があって初めて検定できる
実質的な差 -> 効果量　-> 有意差　と見ていく。効果量を見落とさない。
** すこしぐらいならヘーキ？（頑健性）
正規性、等分散性、独立性
等分散性を前提としないウェルチの検定がある。　t.test(実験、対照) とデ
フォルトの設定。
** 教授からの手紙(独立性の前提)
単純無作為抽出ができれば良い。
できなくても、OKとできる(独立としてよい)か？
どういう状況で抽出したのかを、記述する必要があること多い。

* 二群の平均値差の検定力分析
** 二種類の誤り
  YES,NOの判断をする、この時に、どっちの判断でも間違いのリスクを持っている。
  二分法での判断でも、どっちかの間違いのリスクを犯しながら決定してる。
  違うと判断したけど、実は、踏み込みすぎていた、、、というαの誤り
  同じと判断してるけど、違いを見過ごしてしまった、、、βの誤り
  (*)ここでは、違いがないとの帰無仮説を立てている
  なので、
  違いがあると言う時には、αのリスクにさらされて言明してる。
  同じと言う時には、βの見えない？リスクを踏まえて言明してる。

  自分が考えた比喩
  ボールなのに、ストライクと思って、空振りする確率。(a)
  ストライクが来たらキチンと打ち返せる確率(1-b)
  効果量:打ったらホ吋爛薀鵑砲任るボールかどうか？(棒球とか、、)
  標本数: どこまでボールを引きつけてますか？？？

** 検定力ってそもそもなんですか？
   αとβはトレードオフだけど、和が一定ではないよｌ状況が違うもの。
   α: 帰無仮説が真なのに、棄却してしまう。
   β: 帰無仮説が偽なのに、違いがない(平均値の差の場合)としてしまう。
   １右: 帰無仮説が帰無であって、有意であるとされる確率。
   α、効果量(es)、標本数、検定力(1-β) は検定のカルテット。
** どうして検定力分析が必要なの？
 カルテットを吟味する。
 α: ５％とか1%とか、、決まってる。
- 効果量(es): 平均値の差の時は、標準化された平均値差。標本効果量が目安に
 なる。 効果量を論じるのが目的。で、この効果量の推定値を出して、これが
- 偶然でないとできるかどうか？
- 標本数: 先立って決めないといけない。
- 検定力: この検定の性質を左右してるもの

実質科学的に意味のない差を有意としても、無駄。

** どんな検定力分析があるの？
*** 事前の分析
    標本いくつ必要か？
    n = f(es, (1-β), α)
    esはこれから、、0.2, 0.5, 0.8など
*** 事後の分析
   検定力がどれほどだったか？
   (1-β) = f(nj, no, es, α)
   上の検定力は、標本検定力
*** 明日への分析
    次の実験どうするか？
    標本効果量が分かったので、それを踏まえて。

** ずばり、標本数はいくつ必要だろう。
   いろいろ表が出回ってる。Rなら個別にすぐでるが、、、
   a=0.05, (1-b)=0.8 で、
   - es=0.2 => 788 or 398
   - es=0.5 => 128 or 68
   - es=0.8 => 52 or 30
* 比率の差の検定力分析
* カイ二乗検定の検定力分析
* 相関係数の検定力分析
* １要因分散分析の検定力分析
* 回帰分析の検定力分析
* 多要因分散分析の検定力分析
* 繰り返しのないニ要因分散分析と共分散分析の検定力分析

