* はじめに
  代表値やバラツキ度を計算して、調査対象の全体を把握する
  あくまで、全体
  ばらつきを減らし、リスクを減らすことが可能。
  バラツキが示すもの => 全体がうまくいっているか、いないのか。
  全体の向上を目指す。
  重要な問題なのか、些細な問題なのか
* アクションのために統計学
  1. ブレーンストーミングで問題出し。
  2. KJ法でグループ化
  3. 特性要因図で要因の把握
  4. データ取得のためにチェックシート
  5. パレート図(上位５項目+その他)を書いて、上位からつぶしていく
* グラフはかくも雄弁なり
 hist ヒストグラム(中心は？範囲は？左右対称？ピークは?両端はなだらか？異常値は？)
  => 平均が良い方がいいし、バラツキが少ない方がよい、やりやすい
  ggplot(movies, aes(x=rating)) + stat_bin()
  ggplot(movies, aes(x=rating)) + geom_density()
  ##to create a unit area histogram
  out <- ggplot(movies, aes(x=rating)) + stat_bin(aes(y= ..density..), binwidth=0.1, geom="line", position="identi
  ty")
  out + stat_density(colour="blue", fill=NA)
  
  累積度数で重点施策
  => どこまでやれば、どこまで対策したことになるのか？
  movies.ecdf <- ddply(movies, .(year2000over=year>2000), summarise, rating=unique(rating), ecdf=ecdf(rating)(unique(rating)))
  ggplot(movies.ecdf, aes(rating, ecdf,colour=year2000over)) + geom_step() 
  
* 代表値の諸指標　- 全体を一言で表すなら
  グラフではなく、一つの数字で代表させる
  算術平均と中央値。モードはいらん子か。
* バラツキ度の指標 - リスクを理解しよう
  標準偏差 = 平均値からの距離の二乗の平均(データの個数分の)
  平均からの距離の平均であたりをつけておくことも大切
  概算の標準偏差は、
  - データの多い時、範囲の1/6
  - データの少い時、範囲の1/4
  なので、だいたいその範囲にあると思えばよい。(平均は、範囲の真ん中と
  概算しても良い)
  変動係数 - 標準偏差/平均値で、そのサンプル分布のバラツキ度を規格化す
  る
 ( Zスコアは、ここの取得値が、平均からどれだけずれているのかを、そのサ
  ンプルの標準偏差で規格化したもの)
* 確率 - 不確かな世界を取り仕切る法則
  
* 正規分布 - 最も典型的なばらつきのタイプ
* 二項分布 - よく見かけるもう一つの分布 
* サンプリング論 - １を聞いて１０を知る方法
* 推定 - 未知のものにあたりをつける方法
* 検定 - 却下すべきか、せざるべきか
* 管理図の手法 - マネージメントに求められる統計学
* χ二乗分布 - 分布がわからない時の検定
* F分布と分散分布 - 複数のグループを比較する
  
* 回帰直線　- 風が吹いたら桶屋はもうかるか
* 需要予測 - 売上の予測
* 時系列の分解分析 - 経済時系列予測法


